<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.su</groupId>
    <artifactId>su</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>su-parent</module>
        <module>su-common</module>
        <module>su-feign</module>
        <module>su-grpc</module>
        <module>su-scheduler</module>
        <module>su-cache</module>
        <module>su-mq</module>
        <module>su-message</module>
        <module>su-security</module>
        <module>su-matching-engine</module>
        <module>su-atlas</module>
        <module>xml-service</module>
    </modules>

</project>